### ISSUE TITLE
Extract Operator Transfer Matrix - superfluous iterations

### ISSUE THREAD

**Issue by mattaustin222** [TravelModellingGroup/TMGToolbox#10]
The Extract Operator Transfer Matrix tool looks for how many iterations were done in the assignment and performs traversal analyses for each iteration and then 'blends' them. The called tool does this already natively, so every iteration beyond the 0th is superfluous and hugely inflates tool runtime. 

I've been testing a version of the tool where I remove the classWeights check for CONGESTED_TRANSIT_ASSIGNMENT (within _GetTraversalMatrix) and the end results are identical. Perhaps the easiest fix is just to take out the one if statement and leave the MULTICLASS part.

**Comment by PeterKucirek** [comment]
Just to add some history: this tool was actually written BEFORE the standard tool supported this feature natively. I had to do the blending by hand because I had no other choice.

But yeah, it's probably due for an upgrade now that the blending is no longer needed. Although this assumes that all users should have up-to-date versions of Emme instaled, which I think is a reasonable requirement.

**Comment by JamesVaughan** [comment]
@PeterKucirek Do you remember which version of EMME changed this?

**Comment by PeterKucirek** [comment]
Nope. I searched the Release Notes of Emme 4.2 and 4.1 and cannot find any references to it. The recollection around the office is that it was added some time in 4.1 but nobody remembers the specific version number.

**Comment by bilalyusuf** [comment]
I have adjusted the code for the tool so that the superfluous iterations no longer occur. It should help runtimes significantly.
