### ISSUE TITLE
TMG Toolbox version numbers

### ISSUE THREAD

**Issue by Nasterska** [TravelModellingGroup/TMGToolbox#17]
Would be helpful for TMG Toolbox to have version numbers, to aid in cases where multiple versions exist.

**Comment by PeterKucirek** [comment]
In general, there shouldn't be multiple conflicting versions of a tool; new features should be optional to not break past uses. Usually the only non-optional changes are bug fixes, and you shouldn't be relying on a bug in your use cases. So I would argue that we shouldn't need versions of the full toolbox.

**Comment by Nasterska** [comment]
I can see uses for outdated toolboxes - for example for maintaining consistency with previous project runs. Nevertheless, intentionally maintaining multiple versions of the toolbox is not the only scenario where version numbers (or perhaps dates?) are useful. Another advantage would be the ability to identify whether the toolbox has been updated to the most recent version.

**Comment by PeterKucirek** [comment]
@JamesVaughan @bilalyusuf @BrendanReilly do you have any thoughts on this? I would like to tag this as `wontfix` and close it, but it's probably your call rather than mine.

**Comment by JamesVaughan** [comment]
@PeterKucirek I'm of two minds on this still.  On one hand a version number does make sense to keep but each tool already has a version number.  If it is executed with XTMF the user would hopefully be using the toolbox deployed with XTMF already.

**Comment by JamesVaughan** [comment]
As we are looking towards development of XTMF2 and TMG_Toolbox2 I am going to label this as a won't fix.  In TMG_Toolbox 2 the call functions will be taking arguments in a standardized format so that all individual parameters will be consumed through a JSON string.  This will help maintain backwards compatibility going forwards, and I beleive addressing the real issue raised here.
