### ISSUE TITLE
Added functionality to Import/Export Binary Matrix 

### ISSUE THREAD

**Issue by King-David** [TravelModellingGroup/TMGToolbox#27]
Could the Import and Export Binary Matrix tools have the added ability to handle the file type 'MDF'.

I believe this to be a fairly trivial code change.

**Comment by JamesVaughan** [comment]
@King-David We are unsure of what MDF refers to.  Is it just a renaming of the mtx extension?

**Comment by PeterKucirek** [comment]
PR #28 is ready to add this functionality. It also future-proofs against future deviations (since Emme doesn't specify an extension) by adding an "All files" filter. I tested the tool page on a folder containing MDF, EMXD, MTX, and TXT files

@JamesVaughan I've switched over to MDF as the extension to avoid confusion with EMX (internal binary matrix files). I

**Comment by JamesVaughan** [comment]
#28 is now available through XTMF 1.3.1181
