### ISSUE TITLE
TMG Toolbox Install Error

### ISSUE THREAD

**Issue by mr-illington** [TravelModellingGroup/TMGToolbox#74]
Hi TMG team,

I'm having an issue installing the TMG toolbox - getting the below attached series of errors. For reference, we have tried:

- both TMG toolbox v1.8 and v1.9
- adding the EMME python path to system environment variable
- restarting and running as and not as admin
- we are using EMME 4.3.7

[20220204_TMG_error.txt](https://github.com/TravelModellingGroup/TMGToolbox/files/8004414/20220204_TMG_error.txt)

Wondering if you have seen this behaviour before?
Thanks,
Thomas

**Comment by JamesVaughan** [comment]
It looks like the toolbox is being compiled with a Python3 instance, which is why we are seeing so many errors around print statements.

Are you running the build_toolbox.py directly, or are you using one of the batch files?  If you use the batch files it will use the Python instance that comes with EMME.

**Comment by mr-illington** [comment]
Issue was solved by downloading the compiled version directly from the GitHub releases page. Thanks James
